version: "3"
services:
  web:
    # Recently, a bug was introduced with the latest Create React App version that is causing the React app
    # to exit when starting with Docker Compose. To Resolve this: Add stdin_open property to your docker-compose.yml file
    # Make sure you rebuild your containers after making this change with  docker-compose down && docker-compose up --build
    # Also, If you are using any version of Windows and your React app is not automatically reloading after a code change, you can add this environment variable to your compose file:
    # services:
    #   web:
    #     environment:
    #     - CHOKIDAR_USEPOLLING=true
   
    stdin_open: true 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  # this is a second service for tests
  tests:
    stdin_open: true 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]